---
- name: Manage Ubuntu instances
  hosts: _ubuntu
  become: yes
  gather_facts: yes

  tasks:
    - name: Update package cache (Ubuntu)
      apt:
        update_cache: yes
        upgrade: yes

    - name: Add Docker repository key (Ubuntu)
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository (Ubuntu)
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker CE (Ubuntu)
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Start and enable Docker service (Ubuntu)
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check Docker version (Ubuntu)
      command: docker --version
      register: docker_version_ubuntu

    - name: Display Docker version (Ubuntu)
      debug:
        msg: "Ubuntu Docker version: {{ docker_version_ubuntu.stdout | default('Docker not installed or error') }}"

    - name: Report disk usage (Ubuntu)
      command: df -h
      register: disk_usage_ubuntu

    - name: Show disk usage (Ubuntu)
      debug:
        var: disk_usage_ubuntu.stdout_lines


- name: Manage Amazon Linux instances
  hosts: _amazon
  become: yes
  gather_facts: yes

  tasks:
    - name: Update packages (Amazon Linux)
      yum:
        name: "*"
        state: latest

    - name: Install Docker (Amazon Linux)
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service (Amazon Linux)
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check Docker version (Amazon Linux)
      command: docker --version
      register: docker_version_amazon

    - name: Display Docker version (Amazon Linux)
      debug:
        msg: "Amazon Linux Docker version: {{ docker_version_amazon.stdout | default('Docker not installed or error') }}"

    - name: Report disk usage (Amazon Linux)
      command: df -h
      register: disk_usage_amazon

    - name: Show disk usage (Amazon Linux)
      debug:
        var: disk_usage_amazon.stdout_lines
